on:
  push:
    paths-ignore:
      - "README.md"
      - "changelog.md"
    branches:
      - main

  pull_request:
    paths-ignore:
    - "README.md"
    - "changelog.md"
    branches:
      - main

jobs:
  validate_pwsh:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Run Continuous Integration Pwsh
        shell: pwsh
        run: |
          $PSVersionTable
          cd ./__tests__/unit
          Invoke-Pester -Output Detailed
