on:
  push:
    paths-ignore:
      - "README.md"
      - "changelog.md"
    branches:
      - main

  pull_request:
    paths-ignore:
    - "README.md"
    - "changelog.md"
    branches:
      - main

jobs:
  validate_pwsh:
    name: "validate in pwsh on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, windows-11-arm, ubuntu-latest, ubuntu-24.04-arm, ubuntu-22.04-arm, macos-latest, macos-14-arm64, macos-13-arm64]
    steps:
      - uses: actions/checkout@v1
      - name: Run Continuous Integration Pwsh
        shell: pwsh
        run: |
          $PSVersionTable
          cd ./__tests__/unit
          Invoke-Pester -Output Detailed
