# Publish module workflow
name: publish-module
on:
  workflow_dispatch:
jobs:
  publish-to-gallery:
    runs-on: windows-latest
    steps:
    # checkout
    - uses: actions/checkout@v2
    # validate
    - name: validate module
      shell: pwsh
      run: |
        # validate module
        $result = Test-ModuleManifest -Path ./Hcl2PS.psd1
        if (-not $?) {
            Write-Error 'Module manifest validation was failed.'
            exit 1
        }
        $result | Format-List
    # publish
    - name: publish module
      env:
        NUGET_API_KEY: ${{ secrets.PS_GALLERY_API_KEY }}
      shell: pwsh
      run: |
        # publish module
        if (-not $env:NUGET_API_KEY) {
            Write-Error 'NUGET_API_KEY environment variable not found.'
            exit 1
        }
        Publish-Module -Path . -NuGetApiKey $env:NUGET_API_KEY -Verbose